image: jelaniwoods/appdev2021-foodhub-hotfix

tasks:
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview
  - port: 9515
    onOpen: ignore
  - port: 9514
    onOpen: ignore

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - vortizhe.simple-ruby-erb
    - CraigMaslowski.erb
    - Vense.rails-snippets
    - wingrunr21.vscode-ruby
